CELL 1 — IMPORT & CONNECT DB

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://postgres:rahasia@localhost:5432/superstore_dw")

print("✅ Connected to DB")

✅ Connected to DB

CELL 2 — LOAD CSV

In [4]:
df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')

print("✅ Data loaded")
df.head()

✅ Data loaded

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

CELL 3 — CLEANING

In [5]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df['Postal Code'] = df['Postal Code'].astype(str)

df = df.dropna()

print("✅ Cleaning done")
df.info()

✅ Cleaning done
<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 1.6 MB

CELL 4 — TRUNCATE TABLE (RESET DATA)

In [6]:
with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE fact_sales CASCADE"))
    conn.execute(text("TRUNCATE TABLE dim_location CASCADE"))
    conn.execute(text("TRUNCATE TABLE dim_product CASCADE"))
    conn.execute(text("TRUNCATE TABLE dim_time CASCADE"))

print("🔥 Semua tabel berhasil dikosongkan")

🔥 Semua tabel berhasil dikosongkan

CELL 5 — DIM LOCATION

In [7]:
dim_location = df[['Country','City','State','Postal Code','Region']] \
    .drop_duplicates().reset_index(drop=True)

dim_location.columns = ['country','city','state','postal_code','region']
dim_location['location_id'] = dim_location.index + 1

dim_location.to_sql('dim_location', engine, if_exists='append', index=False)

print("✅ dim_location:", len(dim_location))
dim_location.head()

✅ dim_location: 632

,country,city,state,postal_code,region,location_id
0,United States,Henderson,Kentucky,42420,South,1
1,United States,Los Angeles,California,90036,West,2
2,United States,Fort Lauderdale,Florida,33311,South,3
3,United States,Los Angeles,California,90032,West,4
4,United States,Concord,North Carolina,28027,South,5

CELL 6 — DIM PRODUCT

In [8]:
dim_product = df[['Product ID','Product Name','Category','Sub-Category']] \
    .drop_duplicates(subset=['Product ID'])

dim_product.columns = ['product_id','product_name','category','sub_category']

dim_product.to_sql('dim_product', engine, if_exists='append', index=False)

print("✅ dim_product:", len(dim_product))
dim_product.head()

✅ dim_product: 1862

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

CELL 7 — DIM TIME

In [9]:
dim_time = df[['Order Date']].drop_duplicates().copy()

dim_time['day'] = dim_time['Order Date'].dt.day
dim_time['month'] = dim_time['Order Date'].dt.month
dim_time['month_name'] = dim_time['Order Date'].dt.month_name()
dim_time['quarter'] = dim_time['Order Date'].dt.quarter
dim_time['year'] = dim_time['Order Date'].dt.year

dim_time.columns = ['order_date','day','month','month_name','quarter','year']

dim_time.to_sql('dim_time', engine, if_exists='append', index=False)

print("✅ dim_time:", len(dim_time))
dim_time.head()

✅ dim_time: 1237

   order_date  day  month month_name  quarter  year
0  2016-11-08    8     11   November        4  2016
2  2016-06-12   12      6       June        2  2016
3  2015-10-11   11     10    October        4  2015
5  2014-06-09    9      6       June        2  2014
12 2017-04-15   15      4      April        2  2017

CELL 8 — FACT SALES

In [10]:
location_map = {
    (row['country'], row['city'], row['state'], row['postal_code'], row['region']): row['location_id']
    for _, row in dim_location.iterrows()
}

fact_list = []

for i, row in df.iterrows():
    key = (
        row['Country'],
        row['City'],
        row['State'],
        row['Postal Code'],
        row['Region']
    )

    fact_list.append({
        'row_id': i + 1,
        'order_id': row['Order ID'],
        'customer_id': row['Customer ID'],
        'product_id': row['Product ID'],
        'location_id': location_map.get(key),
        'order_date': row['Order Date'],
        'ship_date': row['Ship Date'],
        'ship_mode': row['Ship Mode'],
        'sales': float(row['Sales']),
        'quantity': int(row['Quantity']),
        'discount': float(row['Discount']),
        'profit': float(row['Profit'])
    })

fact_sales = pd.DataFrame(fact_list)

fact_sales.to_sql('fact_sales', engine, if_exists='append', index=False)

print("✅ fact_sales:", len(fact_sales))
fact_sales.head()

✅ fact_sales: 9994

,row_id,order_id,customer_id,product_id,location_id,order_date,ship_date,ship_mode,sales,quantity,discount,profit
0,1,CA-2016-152156,CG-12520,FUR-BO-10001798,1,2016-11-08,2016-11-11,Second Class,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,CG-12520,FUR-CH-10000454,1,2016-11-08,2016-11-11,Second Class,731.9400,3,0.00,219.5820
2,3,CA-2016-138688,DV-13045,OFF-LA-10000240,2,2016-06-12,2016-06-16,Second Class,14.6200,2,0.00,6.8714
3,4,US-2015-108966,SO-20335,FUR-TA-10000577,3,2015-10-11,2015-10-18,Standard Class,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,SO-20335,OFF-ST-10000760,3,2015-10-11,2015-10-18,Standard Class,22.3680,2,0.20,2.5164

CELL 9 — VALIDASI

In [11]:
with engine.connect() as conn:
    print("📊 CHECK:")
    print("dim_location:", conn.execute(text("SELECT COUNT(*) FROM dim_location")).fetchone()[0])
    print("dim_product:", conn.execute(text("SELECT COUNT(*) FROM dim_product")).fetchone()[0])
    print("dim_time:", conn.execute(text("SELECT COUNT(*) FROM dim_time")).fetchone()[0])
    print("fact_sales:", conn.execute(text("SELECT COUNT(*) FROM fact_sales")).fetchone()[0])

print("🚀 DONE TANPA ERROR")

📊 CHECK:
dim_location: 632
dim_product: 1862
dim_time: 1237
fact_sales: 9994
🚀 DONE TANPA ERROR